apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  labels:
    app: flask 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask 
  template:
    metadata:
      labels:
        app: flask 
    spec:
      containers:
      - name: flaskapp
        image: karan6190/app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flaskservice
spec:
  selector:
    app: flask
  ports:
    - port: 80        # External port exposed by the service
      targetPort: 5000 # Port on the pod
      nodePort: 31080  # Optional: Specify a node port (31080 in this case)
  type: NodePort       # Change the type to NodePort